"""Consolidate frequency storage - fix 3

Revision ID: 4daa3fd87e71
Revises: aa1ae4c7a6cc
Create Date: 2026-01-28 15:33:00.947361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4daa3fd87e71'
down_revision: Union[str, Sequence[str], None] = 'aa1ae4c7a6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('product_definitions')]
    
    if 'frequency_class' not in columns:
        from sqlalchemy.dialects import postgresql
        op.add_column('product_definitions', sa.Column('frequency_class', postgresql.ENUM('A', 'B', 'C', name='frequencyclass', create_type=False), server_default='C', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_definitions', 'frequency_class')
    # ### end Alembic commands ###
