"""remove_is_active

Revision ID: 6862556d5557
Revises: 0b149ce3f394
Create Date: 2026-01-08 15:38:23.614708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6862556d5557'
down_revision: Union[str, Sequence[str], None] = '0b149ce3f394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racks', sa.Column('distance_from_exit_m', sa.Float(), nullable=True))
    op.drop_constraint(op.f('_rack_position_uc'), 'stock_items', type_='unique')
    op.create_unique_constraint('unique_rack_position', 'stock_items', ['rack_id', 'position_row', 'position_col'])
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_2fa_enabled')
    op.drop_constraint('unique_rack_position', 'stock_items', type_='unique')
    op.create_unique_constraint(op.f('_rack_position_uc'), 'stock_items', ['rack_id', 'position_row', 'position_col'], postgresql_nulls_not_distinct=False)
    op.drop_column('racks', 'distance_from_exit_m')
    # ### end Alembic commands ###
