"""add y_position to stock_items

Revision ID: 9274bdbc28a1
Revises: 691dc89583dc
Create Date: 2026-03-26 18:41:47.424525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9274bdbc28a1'
down_revision: Union[str, Sequence[str], None] = '691dc89583dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_items', sa.Column('y_position', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('unique_rack_position'), 'stock_items', type_='unique')
    op.create_unique_constraint('unique_rack_position', 'stock_items', ['rack_id', 'position_row', 'position_col', 'y_position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_rack_position', 'stock_items', type_='unique')
    op.create_unique_constraint(op.f('unique_rack_position'), 'stock_items', ['rack_id', 'position_row', 'position_col'], postgresql_nulls_not_distinct=False)
    op.drop_column('stock_items', 'y_position')
    # ### end Alembic commands ###
