"""add x y to alerts

Revision ID: 9396d1f01911
Revises: d10e9cef0ee4
Create Date: 2026-01-08 19:26:10.094102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9396d1f01911'
down_revision: Union[str, Sequence[str], None] = 'd10e9cef0ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'y')
    op.drop_column('alerts', 'x')
    # ### end Alembic commands ###
