"""Add product_stats - retry

Revision ID: aa1ae4c7a6cc
Revises: 0effbe93c03a
Create Date: 2026-01-28 15:20:11.498615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1ae4c7a6cc'
down_revision: Union[str, Sequence[str], None] = '0effbe93c03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    
    # Create enum type safely if it doesn't exist
    frequency_enum = postgresql.ENUM('A', 'B', 'C', name='frequencyclass')
    frequency_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('product_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pick_count', sa.Integer(), nullable=False),
    sa.Column('total_since_last_update', sa.Integer(), nullable=False),
    sa.Column('frequency', postgresql.ENUM('A', 'B', 'C', name='frequencyclass', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_stats_id'), 'product_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_stats_id'), table_name='product_stats')
    op.drop_table('product_stats')
    # ### end Alembic commands ###
