"""add_comment_field

Revision ID: d2c4d583d806
Revises: a3671679a64e
Create Date: 2026-01-14 22:13:14.802362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c4d583d806'
down_revision: Union[str, Sequence[str], None] = 'a3671679a64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_definitions', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_definitions', 'comment')
    # ### end Alembic commands ###
