
import csv
import io
import random
import uuid

def generate_csv_content(num_rows: int) -> str:
    """
    Generates a CSV string with random product definitions.
    Format matches the project requirement:
    #Nazwa;Id;Zdjecie;TempMin;TempMax;Waga;SzerokoscMm;WysokoscMm;GlebokoscMm;Komentarz;TerminWaznosciDni;CzyNiebezpieczny
    """
    output = io.StringIO()
    # Add comment lines as per spec
    output.write("#Linie zaczynające się od znaku '#' oznaczają komentarz i powinny być ignorowane.\n")
    output.write("#Nazwa;Id;Zdjecie;TempMin;TempMax;Waga;SzerokoscMm;WysokoscMm;GlebokoscMm;Komentarz;TerminWaznosciDni;CzyNiebezpieczny\n")
    
    writer = csv.writer(output, delimiter=';', lineterminator='\n')
    
    for i in range(num_rows):
        name = f"Produkt_Perf_{i}_{uuid.uuid4().hex[:6]}"
        barcode = f"BAR{uuid.uuid4().hex[:10].upper()}"
        photo = ""
        temp_min = random.randint(-10, 15)
        temp_max = temp_min + random.randint(5, 20)
        weight = round(random.uniform(0.1, 50.0), 2)
        width = random.randint(10, 500)
        height = random.randint(10, 500)
        depth = random.randint(10, 500)
        comment = "Generated by Locust"
        expiry_days = random.randint(30, 365)
        is_dangerous = "TRUE" if random.random() < 0.05 else "FALSE"
        
        writer.writerow([
            name,
            barcode,
            photo,
            temp_min,
            temp_max,
            weight,
            width,
            height,
            depth,
            comment,
            expiry_days,
            is_dangerous
        ])
        
    return output.getvalue()

import base64

def generate_dummy_image():
    """
    Generates a valid small JPG image in memory (1x1 pixel).
    Uses a known valid Base64 string to avoid byte literal issues.
    """
    # 1x1 pixel white JPEG
    base64_jpg = "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigD//2Q=="
    return base64.b64decode(base64_jpg)
