from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.ext.asyncio import AsyncSession

from app.core import deps
from app.database.session import get_db
from app.database.models.user import User
from app.schemas.auth import (
    Token,
    TwoFactorSetupResponse,
    TwoFactorVerifyRequest,
    TwoFactorLoginRequest,
    PasswordChangeRequest,
)
from app.schemas.msg import Msg
from app.services.auth_service import AuthService

router = APIRouter()


@router.post(
    "/login",
    response_model=Token,
    summary="Login user",
    responses={400: {"description": "Incorrect login or password"}, 401: {"description": "Inactive user"}},
)
async def login_access_token(
    form_data: OAuth2PasswordRequestForm = Depends(), db: AsyncSession = Depends(get_db)
) -> Any:
    """
    OAuth2 compatible token login, get an access token for future requests.

    - If 2FA is enabled for the user, returns a temporary token with `is_2fa_required=True`.
    - If 2FA is disabled, returns a full access token.
    """
    user = await AuthService.authenticate_user(
        db, form_data.username, form_data.password
    )
    if not user:
        raise HTTPException(status_code=400, detail="Niepoprawny login lub hasło")

    return AuthService.create_login_token(user)


@router.post(
    "/2fa/setup",
    response_model=TwoFactorSetupResponse,
    summary="Setup 2FA",
    responses={401: {"description": "Not authenticated"}},
)
async def setup_2fa(
    current_user: User = Depends(deps.get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Any:
    """
    Initiate 2FA setup for the current user.

    Generates a new TOTP secret and returns:
    - **secret**: The raw secret key.
    - **qr_code_url**: The provisioning URI.
    - **qr_code_image**: Base64 encoded PNG image of the QR code.
    """
    return await AuthService.setup_2fa(db, current_user)


@router.post(
    "/2fa/verify",
    response_model=Msg,
    summary="Verify and Enable 2FA",
    responses={
        400: {"description": "Invalid code or 2FA not initiated"},
        401: {"description": "Not authenticated"},
    },
)
async def verify_2fa_setup(
    body: TwoFactorVerifyRequest,
    current_user: User = Depends(deps.get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Any:
    """
    Verify the code to ENABLE 2FA.

    Requires the user to provide a valid code generated by their authenticator app
    to confirm the setup and activate 2FA on their account.
    """
    success = await AuthService.verify_and_enable_2fa(db, current_user, body.code)
    if not success:
        raise HTTPException(status_code=400, detail="Invalid code")

    return {"message": "2FA włączone pomyślnie"}


@router.post(
    "/2fa/login",
    response_model=Token,
    summary="Complete 2FA Login",
    responses={
        400: {"description": "Invalid code or 2FA not enabled"},
        401: {"description": "Invalid token or User not found"},
    },
)
async def login_2fa(
    body: TwoFactorLoginRequest, db: AsyncSession = Depends(get_db)
) -> Any:
    """
    Complete login with 2FA code.

    Requires:
    - **token**: The temporary access token received from `/login` (when `is_2fa_required=True`).
    - **code**: The TOTP code from the authenticator app.

    Returns a full access token if successful.
    """
    return await AuthService.login_2fa(db, body.token, body.code)


@router.post(
    "/change-password",
    response_model=Msg,
    summary="Change user password",
    responses={
        400: {"description": "Incorrect current password"},
        401: {"description": "Not authenticated"},
    },
)
async def change_password(
    body: PasswordChangeRequest,
    current_user: User = Depends(deps.get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Any:
    """
    Change the current user's password.

    Requires:
    - **old_password**: The user's current password for verification.
    - **new_password**: The new password (minimum 8 characters).
    - **confirm_password**: Confirmation of the new password (must match).

    Returns a success message if the password is changed successfully.
    """
    await AuthService.change_password(
        db, current_user, body.old_password, body.new_password
    )
    return {"message": "Hasło zmienione pomyślnie"}

